=== tanisavina/Afisha/src/main/resources/AfishaXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.htp.by"
	targetNamespace="http://www.htp.by" elementFormDefault="qualified">
	<xs:element name="afisha" type="afishaType" />
	<xs:element name="events" type="eventsType" />
	<xs:element name="event" type="eventType" />
	<xs:complexType name="afishaType">
		<xs:sequence>
		<xs:element name="events" type="eventsType" />
		</xs:sequence>
	<xs:attribute name="city" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="eventsType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="film" type="eventFilm" maxOccurs="unbounded" />
			<xs:element name="opera" type="eventOpera" maxOccurs="unbounded" />
			<xs:element name="exhibition" type="eventExhibition" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="eventType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="date" type="xs:date" />
			<xs:element name="time" type="xs:string" />
			<xs:element name="place" type="xs:string" />
			<xs:element name="cost" type="xs:double" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="eventFilm">
		<xs:complexContent>
			<xs:extension base="eventType">
				<xs:sequence>
					<xs:element name="genre">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="drama" />
								<xs:enumeration value="horor" />
								<xs:enumeration value="comedy" />
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="rating" type="xs:double" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="eventOpera">
		<xs:complexContent>
			<xs:extension base="eventType">
				<xs:sequence>
					<xs:element name="singer" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="eventExhibition">
		<xs:complexContent>
			<xs:extension base="eventType">
				<xs:sequence>
					<xs:element name="author" type="xs:string" />
					<xs:element name="theme" type="xs:string" />					
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>	
</xs:schema>

=== tanisavina/Afisha/src/main/resources/Afisha.xml
<?xml version="1.0" encoding="UTF-8"?>
<afisha city="Minsk" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.htp.by" xsi:schemaLocation="http://www.htp.by AfishaXMLSchema.xsd"> 
	<events>
		<film>
			<title>White shark</title>
			<date>2016-11-12</date>
			<time>18:30</time>
			<place>Moskva</place>
			<cost>2.00</cost>
			<genre>drama</genre>
			<rating>5</rating>
		</film>
		<opera>
			<title>Snegurochka</title>
			<date>2016-11-23</date>
			<time>17:00</time>
			<place>Russkiy</place>
			<cost>4.50</cost>
			<singer>Ivanov</singer>
		</opera>
		<exhibition>
			<title>Impressionizm</title>
			<date>2016-11-30</date>
			<time>09:00</time>
			<place>Istor</place>
			<cost>1.50</cost>
			<author>Petrov</author>
			<theme>Art</theme>
		</exhibition>		
	</events>
</afisha>
